# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

good_turing_multinom <- function(Obs, Freq, confid_factor) {
    .Call(`_variantprobs_good_turing_multinom`, Obs, Freq, confid_factor)
}

